name: redis
home: https://github.com/deis/redis
version: <Will be populated by the ci before publishing the chart>
description: A Redis database for use inside a Kubernetes cluster.
maintainers:
  - name: Deis Team
    email: engineering@deis.com
